stages:
  preprocessing:
    cmd: python src/preprocessing.py
    deps:
      - data/raw
      - src/preprocessing.py
    outs:
      - data/processed
  
  models:
    cmd: python src/models.py
    deps:
      - data/processed
      - src/models.py
    outs:
      - data/outputs/knn_model.pkl
      - data/outputs/LR_model.pkl
      - data/outputs/RF_model.pkl
      - data/outputs/GBoost_model.pkl
      - data/outputs/LTV.csv

  causal:
    cmd: python src/causal.py
    deps:
      - data/processed
      - src/causal.py
    outs:
      - data/outputs/AB_test_result.csv
      - data/outputs/individual_treatment_effects.csv

  policy:
    cmd: python src/policy.py
    deps:
        - data/outputs/individual_treatment_effects.csv
        - src/policy.py
    metrics:
        - data/outputs/targeting_customer.csv
